### PR TITLE
Update samtools in some mulled containers

### PR DESCRIPTION
**Pull request by nvnieuwk**

### CODE REVIEW

**Comment by bgruening** [comment]
Is there any new feature in samtools that you need? Please keep in mind that someone needs to pay the bill for those containers

**Comment by nvnieuwk** [comment]
Not really, just a version bump. I understand if you don't want to submit these because of this

**Comment by FriederikeHanssen** [comment]
For the mapping mulled containers: there seem to be several bug fixes for dealing with CRAM files and sorting: https://github.com/samtools/samtools/releases/

**Comment by bgruening** [comment]
Are you hitting those bugs? :)
I just want to raise the issue of environmental impact and cost. So there is a tradeoff. Updating all containers with samtools, with every samtools version is not scalable imho.

An alternative would be that you run samtools as a separate container - which we already provide.

**Comment by nvnieuwk** [comment]
I'm personally not hitting them, @FriederikeHanssen do you know of anyone having issues?

**Comment by nvnieuwk** [comment]
Okay, I'll just remove some of the lesser used containers. We can still add them later if needed. Thanks!

**Comment by nvnieuwk** [comment]
@bgruening all PRs are done and CI is passing

**Comment by nvnieuwk** [comment]
@bgruening I fixed the CI failures :)

**Comment by bgruening** [comment]
Thanks

**Comment by nvnieuwk** [comment]
Thank you for the merges! The nf-core community will be very happy :partying_face:

**Comment by bgruening** [comment]
Your welcome!

**Pull request merged**
