### PR TITLE
Add biopython and pigz

### PR DESCRIPTION
**Pull request by rivera10**

### CODE REVIEW

**Comment by bgruening** [comment]
Is pigz an official dependency of biopython?

**Comment by rivera10** [comment]
Hello @bgruening,

It is not. We are using this combination in our tools to handle big files after we use biopython.

Thanks

**Comment by bgruening** [comment]
Can you not stream from one container to the other? Will merge when it turns green.

**Comment by rivera10** [comment]
In theory I could but I end with two files in two different processes (i.e. uncompressed original and compressed file). Using both in one process reduces disk space usage.

**Pull request merged**
