### PR TITLE
Added container for tumorID with SCEVAN dependencies

### PR DESCRIPTION
**Pull request by LiliyaBioinf**
This PR adds a new multi-package container to support the TumorID workflow. It updates the multi-package container based on `quay.io/biocontainers/r-scevan:latest`, ensuring that only essential R and Bioconductor packages are included.

### CODE REVIEW

**Comment by LiliyaBioinf** [comment]
@bgruening  No, this PR introduces a multipackage container tailored for running SCEVAN workflows. The container is based on the existing r-scevan image, and it includes additional essential packages to support visualization, data manipulation, and analysis tasks commonly needed in single-cell experiments.

**Comment by bgruening** [comment]
Ok, the current combination of packages fails. Can you look at it?

**Comment by LiliyaBioinf** [comment]
@bgruening hi, could you help me, please, is supposed to work, but the building process is very long. Maybe you say what is the problem in my PR?

**Comment by bgruening** [comment]
I will have a look as soon as possible.

**Comment by LiliyaBioinf** [comment]
Where and how I can find my container?

**Comment by bgruening** [comment]
Try this one: `quay.io/biocontainers/mulled-v2-0b17a5aa60f5d02d3c7656b6b6d3732e81290f05:0`

**Pull request merged**
