### PR TITLE
fgbio=2.0.2,r-base=4.2.3,r-ggplot2=3.4.2

### PR DESCRIPTION
**Pull request by ajtock**
This container should enable fgbio tools to generate summary plots using ggplot2

### CODE REVIEW

**Comment by bgruening** [comment]
That should probably be added as dependencies to the fgbio package, isn't it?

**Comment by ajtock** [comment]
Unfortunately separate R and ggplot2 installation seems to be required. E.g., under "Requirements" for the fgbio tool [CollectDuplexSeqMetrics](http://fulcrumgenomics.github.io/fgbio/tools/latest/CollectDuplexSeqMetrics.html): "For plots to be generated R must be installed and the ggplot2 package installed with suggested dependencies. Successfully executing the following in R will ensure a working installation:
`install.packages("ggplot2", repos="http://cran.us.r-project.org", dependencies=TRUE)`"

**Comment by ajtock** [comment]
Sorry @bgruening you're right - I looked in the conda-meta directory after installing fgbio and found that base R and ggplot2 are indeed installed with it, so no need to create this container.

**Comment by bgruening** [comment]
Thanks for looking that up!

**Pull request closed without merging**
