### PR TITLE
Kept initial line

### PR DESCRIPTION
**Pull request by thatzopoulos**
Added the previous packages as informed to do in the pull request comment

### CODE REVIEW

**Comment by bgruening** [comment]
Hasn't worked. If you look at the diff it is still removed.

**Comment by thatzopoulos** [comment]
Should I add my packages to a second line and not append them to the existing packages of bwa and samtools?

**Comment by bgruening** [comment]
Yes, second line :)

**Comment by bgruening** [comment]
The comma was not needed, I removed it. Thanks for your contribution.

**Comment by bgruening** [comment]
depending on how long a build will take and how many other images are build currently, you image will be available in a few minutes - but I guess not later then 1h

**Comment by thatzopoulos** [comment]
Thank you, do you know where I can find the name of the image when I am able to pull it?

**Comment by bgruening** [comment]
Mh, good question :)
You can create the some with this tool: http://biocontainers.pro/multi-package-containers/
But we probably need a better way to indicate this ... ideas?

**Comment by thatzopoulos** [comment]
The Travis build has a REPO variable, is that the name I pull?
REPO='quay.io/biocontainers/mulled-v2-479afae422967342fa0b4c960279d955201989eb:a81d2ea66ef55b9de15ac6e4ab2b0bc87221c115-0'

**Comment by bgruening** [comment]
Yes. :)

**Comment by bgruening** [comment]
https://quay.io/repository/biocontainers/mulled-v2-479afae422967342fa0b4c960279d955201989eb?tab=tags

**Comment by thatzopoulos** [comment]
Thank you for all your help, I appreciate it

**Comment by bgruening** [comment]
Sure thing! Let us know how it goes. This is a new project and we appreciate any feedback!

**Pull request merged**
