### PR TITLE
Update hash.tsv

### PR DESCRIPTION
**Pull request by ryancey1**
A simple `DiffBind` container with dependencies for differential accessibility workflow. `csaw` is necessary when background normalization is desired, and this does not ship with the current [`bioconductor-diffbind`](https://quay.io/repository/biocontainers/bioconductor-diffbind) container available.

### CODE REVIEW

**Comment by ryancey1** [comment]
Simple `DiffBind` container with dependencies for differential accessibility workflow

**Comment by bgruening** [comment]
Ther is also edger and others included. Those containers are not intended to contain entire workflows. Please deco pose your workflow in steps and reuse smaller containers. This will make the maintainence and storage of the container for sufficient.

**Comment by ryancey1** [comment]
@bgruening,`DiffBind` by default only imports `DESeq2`, so if a user wishes to use `edgeR` or run background normalization in their DA workflow, they need to import `edgeR` and `csaw` separately. I removed others that are installed/imported with `DiffBind` (BiocParallel, base, ggplot2), as they were redundant. Thank you for your review.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @ryancey1

**Comment by Bioninbo** [comment]
Hello. Where is this container located? Nothing appears with 
`mulled-search --channel bioconda --search bioconductor-diffbind bioconductor-edger | grep mulled`

**Comment by ryancey1** [comment]
@Bioninbo you can use the container located [here](https://quay.io/repository/biocontainers/mulled-v2-9ec5efd66a9a09ea4f9ad9bad5485675f031aeb4). That's the container built/pushed from this PR.

**Comment by Bioninbo** [comment]
Great! Thanks @ryancey1!! Any idea how I could have located this container? For next time, do you maybe know how I could have located this container? And why my mulled-search queries didn't work?

**Comment by Bioninbo** [comment]
I get an error.   `no item called "package:parallel" on the search list` even though I set the argument `bParallel = F`. Does the container/package work for you?

**Comment by ryancey1** [comment]
@Bioninbo I don't believe loading `DiffBind` automatically imports the `parallel` package. Try running `library(parallel)` and rerun that line.

**Comment by Bioninbo** [comment]
> @Bioninbo I don't believe loading `DiffBind` automatically imports the `parallel` package. Try running `library(parallel)` and rerun that line.

Yes it works! Thanks a lot!

**Comment by Bioninbo** [comment]
> 

Maybe @bgruening will have a suggestion?

**Comment by Bioninbo** [comment]
> @Bioninbo I think I got the mulled-v2 hash from the build log, if I remember correctly. I'm not sure how to look for multi-package containers using the `mulled-*` toolset.

Maybe @bgruening will have a suggestion?

**Pull request merged**
