### PR TITLE
Requesting bwa=0.7.17 + samtools=1.9

### PR DESCRIPTION
**Pull request by tamuanand**
Requesting multi-container with bwa=0.7.17,samtools=1.9

### CODE REVIEW

**Comment by bgruening** [comment]
@tamuanand hi! Can I convince you to use https://github.com/BioContainers/multi-package-containers/blob/e51f9fe15afe58fc14d9ff7db5759a7c93df2806/combinations/mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40:23592e4ad15ca2acfca18facab87a1ce22c49da1-0.tsv instead? Or do you need this version of samtools?

**Comment by tamuanand** [comment]
Hi @bgruening 

I have a requirement to use this specific version of samtools (1.9) 

Thanks

**Comment by tamuanand** [comment]
Hi @bgruening 

A quick question: How will I know if this multi-container be available for docker pull via quay if I search using the `mulled` utilitity

Thanks

**Comment by bgruening** [comment]
The container will be available, 10min after the merge, but I cancelled this build as you created a very similar PR with the same tools. So this container will not be created.

**Comment by tamuanand** [comment]
I mentioned reasons why not to cancel this build - reasons mentioned here: https://github.com/BioContainers/multi-package-containers/pull/1781#issuecomment-875151999

> I cancelled this build as you created a very similar PR with the same tools. So this container will not be created.

Thanks

**Pull request merged**
