### PR TITLE
Bff image creation

### PR DESCRIPTION
**Pull request by opetryk**
Creating image to BFF module

### CODE REVIEW

**Comment by opetryk** [comment]
task: https://github.com/nf-core/modules/issues/5066

**Comment by jonasscheid** [comment]
Hi @bgruening! Is your approval required here to run multiple CI runs?

**Comment by opetryk** [comment]
@bgruening can I ask for your approval one time more to run pipeline on CI? I did resolve conflict packages by checking it locally on conda environment

**Comment by opetryk** [comment]
@bgruening thank you! All checks passed, can I ask you for approving/merging it?

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
