### PR TITLE
pathview: pin openssl

### PR DESCRIPTION
**Pull request by bernt-matthias**
fixes https://github.com/galaxyproject/tools-iuc/issues/4901

Alternatively we could add openssl as requirement to the IUC pathview tool.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
OK. You mean that we should not create a new build with changed requirements? What is the right way then? 

I guess the right way would be to fix a conda package. Problem is that I have no idea which one .. just that the is a conda package that apparently misses a pin for the openssl version. Also adding such a pin for a likely outdated version might be particularly annoying. 

Alternatively a PR for IUC adding a requirement .. ?

**Comment by mvdbeek** [comment]
> is a conda package that apparently misses a pin for the openssl version.

yes. the one that makes the download request, probably curl ? (https://www.rdocumentation.org/packages/curl/versions/5.0.0/topics/curl_fetch_memory )

> Alternatively a PR for IUC adding a requirement .. ?

I think that's fine as plan B, but fixing the curl package will prevent similar things in the future

**Comment by bernt-matthias** [comment]
In the container (where pathview fails) I see 

```
> library('curl')
Using libcurl 7.83.0 with OpenSSL/3.0.3
```

Problem is that I can't find a URL where `curl::curl_fetch_memory` fails .. and a test case would be nice.

**Comment by mvdbeek** [comment]
Can you find out what url pathview is failing on ?

**Pull request closed without merging**
