### PR TITLE
bump build of mulled-v2-eb9e7907c7a753917c1e4d7a64384c047429618a:bcea566aaf2a8cd09765df369b45c50e0b7e9f18

### PR DESCRIPTION
**Pull request by lldelisle**

### CODE REVIEW

**Comment by lldelisle** [comment]
Before merging, could someone check that when using the image the following command is not raising errors:
```
bigwigAverage --version
```
(With the previous built it was:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/deeptools/parserCommon.py", line 4, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bigwigAverage", line 7, in <module>
    from deeptools.bigwigAverage import main
  File "/usr/local/lib/python3.6/site-packages/deeptools/bigwigAverage.py", line 8, in <module>
    from deeptools import parserCommon
  File "/usr/local/lib/python3.6/site-packages/deeptools/parserCommon.py", line 6, in <module>
    from importlib_metadata import version
ModuleNotFoundError: No module named 'importlib_metadata'


```
)

**Comment by lldelisle** [comment]
@bgruening if you can help with this?

**Comment by bgruening** [comment]
We can merge and test?

**Comment by lldelisle** [comment]
It worked but I got another dependency problem...

**Pull request merged**
