### PR TITLE
Update bioconda default base image

### PR DESCRIPTION
**Pull request by mvdbeek**
That'll only have an effect on rows that don't specify the image explicitly.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by mvdbeek** [comment]
I have a vague memory of there being a problem (hence the pin) ... let me see what that was

**Comment by mvdbeek** [comment]
OK, this should fix it: https://github.com/galaxyproject/galaxy/pull/11979

**Comment by mvdbeek** [comment]
@bgruening we got a new galaxy-tool-util, but the build is failing now with some unavailable packages ... should we drop that entry ?

**Comment by mvdbeek** [comment]
Yay, seems to work ... I have no idea what's up with the combinations I had to delete though ... can we figure out if those images had ever been built correctly ?

**Comment by bgruening** [comment]
I think they have been build 3 years ago for the encode project. But the package are not in the conda index anymore, not sure why :(

Danke Marius!

**Pull request merged**
