### PR TITLE
Add environment for busco

### PR DESCRIPTION
**Pull request by skrakau**
Add: 
`python=3.7.3,prodigal=2.6.3,augustus=3.3.3,diamond=2.0.1,hmmer=3.1b2,blast=2.10.1,sepp=4.3.10,cairo=1.16.0,r-rgtk2=2.20.36,fonts-conda-ecosystem=1,r-base=4.0.2,r-ggplot2=3.3.2,busco=4.1.4`

### CODE REVIEW

**Comment by bgruening** [comment]
@skrakau is the plan busco container not working for you? If the aim is to have busco running in a container, and it is not currently, we should fix the bioconda recipe I think.

**Comment by skrakau** [comment]
Hi @bgruening, I am not sure. There were multiple issues a while ago, some related to the version of external tools, some only with the additional plotting script of Busco and in combination with a specific nf-core base image. I am currently migrating a nextflow pipeline to DSL2 and started using BioContainers, and thought it would be good to keep the exact versions which worked for us at least for the beginning.

**Comment by bgruening** [comment]
I just want to make sure that the busco container is working. And if not we should fix this container and not work around here. We still need to keep those containers minimal and reusable. Let me know if you prefer to get this merged and we will do so.

**Comment by skrakau** [comment]
Hi @bgruening, I tested it again and when running the busco script `generate_plot.py` with the`busco:4.1.4--py_0`container I get the following error:
```
  INFO:	****************** Start plot generation at 02/15/2021 12:13:55 ******************
  INFO:	Load data ...
  INFO:	Loaded ./short_summary.specific.bacteria_odb10.MEGAHIT-minigut1_1_fa.txt successfully
  INFO:	Generate the R code ...
  INFO:	Run the R code ...
  INFO:
  [1] "Plotting the figure ..."

  INFO:	Plot generation done. Total running time: 1.7865371704101562 seconds
  INFO:	Results written in ./

Command error:
  ERROR:

   *** caught segfault ***
  address (nil), cause 'memory not mapped'

  Traceback:
   1: cairoVersion()
   2: grSoftVersion()
   3: symbolType1support()
   4: optionSymbolFont(d$symbolfamily)
   5: grDevices::png(..., res = dpi, units = "in")
   6: dev(filename = filename, width = dim[1], height = dim[2], ...)
   7: ggsave(figure, file = my_output, width = my_width, height = my_height,     unit = my_unit)
  An irrecoverable exception occurred. R is aborting now ...
```
I guess this particular script is not used by most people who use busco. In the past I could avoid this error by specifying:
```
  - conda-forge::cairo=1.16.0
  - conda-forge::r-rgtk2=2.20.36 
```
(in combination with `RUN apt-get install -y libxt6` in the Dockerfile, not sure about this part for biocontainers).

**Comment by skrakau** [comment]
`fonts-conda-ecosystem=1` I added due to a problem with missing fonts in the resulting plots, I don't yet if this is still a problem.

**Comment by skrakau** [comment]
the bioconda recipe was updated accordingly, see https://github.com/bioconda/bioconda-recipes/pull/26883

**Comment by bgruening** [comment]
Thanks a lot @skrakau for your time to fix it that way!

**Pull request closed without merging**
