### PR TITLE
Add missing dependency to container 

### PR DESCRIPTION
**Pull request by rivera10**

### CODE REVIEW

**Comment by rivera10** [comment]
@bgruening Ready to merge. Thanks

**Comment by bgruening** [comment]
Thanks @rivera10

**Comment by rsuchecki** [comment]
Should this one be on-line now @bgruening / @rivera10 or am I  looking in the wrong place(s)?

```sh
#DOCKER
docker pull quay.io/biocontainers/mulled-v2-848eb9b6a829414c79e64bc96d43109620d1cfd9:869b2b6d573ee185276907ccda7237a29552a952-0
Error response from daemon: unauthorized: access to the requested resource is not authoriz

#SINGULARITY (via Nextflow)
Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-mulled-v2-848eb9b6a829414c79e64bc96d43109620d1cfd9-869b2b6d573ee185276907ccda7237a29552a952-0.img.pulling.1622428858048 https://depot.galaxyproject.org/singularity/mulled-v2-848eb9b6a829414c79e64bc96d43109620d1cfd9:869b2b6d573ee185276907ccda7237a29552a952-0 > /dev/null
  status : 255
  message:
    INFO:    Downloading network image
    FATAL:   the requested image was not found
```

**Comment by rivera10** [comment]
Yes, that is the correct container 
```
mulled-v2-848eb9b6a829414c79e64bc96d43109620d1cfd9:869b2b6d573ee185276907ccda7237a29552a952-0
```
For me is working fine using 
```
docker run -ti quay.io/biocontainers/mulled-v2-848eb9b6a829414c79e64bc96d43109620d1cfd9:869b2b6d573ee185276907ccda7237a29552a952-0
```
or 
```
singularity run https://depot.galaxyproject.org/singularity/mulled-v2-962eae98c9ff8d5b31e1df7e41a355a99e1152c4:0ed9db56fd54cfea67041f80bdd8b8fac575112f-0
```
I already added it to the nextflow script (see https://github.com/PalMuc/TransPi/commit/92a2083e30153407c85b8c1a8220400b863b10a8). I also did a test and it is working fine with the pipeline. I suggest to pull the repository again so you have the recent changes needed for the pipeline to work with the container.

**Pull request merged**
