### PR TITLE
Hisat2 + samtools + StringTie 

### PR DESCRIPTION
**Pull request by rsuchecki**
A combination useful for workflows where a BAM can be discarded immediately after a StringTie assembly

### CODE REVIEW

**Comment by bgruening** [comment]
Wouldn't it be better to have two containers here? hisat and stringtie?

**Comment by rsuchecki** [comment]
> Wouldn't it be better to have two containers here? hisat and stringtie?

That was my initial approach and a suitable mulled container already exists (hisat2+samtools) and there is a separate stringtie container.


This is for a scenario where `hisat | samtools sort | stringtie ` to generate GTF and/or abundance, which saves ~ 20TB storage for my workflow by not storing BAMs. This is partly due to limitations/design of Nextflow - where 

1. I can't "connect"  2 processes via stdin/out or otherwise use 2 containers in a process to do the above task in one step 
2. hisat process cache would be invalidated if I simply removed the BAM at the end of the downstream stringtie process (can be circumvented using hacks) so re-runs of the workflow would lead to both hisat2 and stringtie being re-run.

Either way, the unnecessary BAM would be written to disk, at least briefly, likely with some ugly hacks. 

I appreciate that this may be  too niche of a scenario and I should perhaps build the container myself.

**Comment by bgruening** [comment]
My problem with this is, that this opens up an explosion of containers that we would need to create and maintain. Arbitrary piping scenarios + different versions.

I'm fine with merging this one, but we should not start to make this a habit.

**Comment by rsuchecki** [comment]
Many thanks Björn!

Agree about the general point - still keen to use the build framework but should be pushing to user/organisation space.

**Comment by rsuchecki** [comment]
Should probably delete the created image as the package spec was malformed - apologies.

**Pull request closed without merging**
