### PR TITLE
Change pgzip container to pigz, pgzip conda package appears to be broken

### PR DESCRIPTION
**Pull request by lrauschning**

### CODE REVIEW

**Comment by bgruening** [comment]
@lrauschning why is the package broken? Is that reported upstream?

**Comment by lrauschning** [comment]
Sorry, should have been a bit more descriptive in the PR and not just rephrased my commit message.
I noticed yesterday while updating a PR to NF-Core I had made that I copy-pasted the wrong package from anaconda.org in #2792  – concretely, the Python package [pgzip](https://pypi.org/project/pgzip/) instead of the commandline tool [pigz](https://zlib.net/pigz/). That broke tests on my local machine, the package itself is fine as far as I can tell.

**Comment by lrauschning** [comment]
As there was previously no pgzip container in hash.tsv, I propose changing that to pigz (which is the one I need containerized for the NF-Core module).

**Comment by bgruening** [comment]
Ok, thanks for the explanation. Can you please add your new container to the file without removing the old line. Thanks.

**Comment by lrauschning** [comment]
Sure, one moment.

**Pull request merged**
