### PR TITLE
CI: Add cnvkit=0.9.8,samtools=1.15.1

### PR DESCRIPTION
**Pull request by YeHW**
Add multi-package-containers:
`cnvkit=0.9.8,samtools=1.15.1`

### CODE REVIEW

**Comment by YeHW** [comment]
I'd be very appreciative if anyone could help me to figure out why build fails :)

**Comment by bgruening** [comment]
Maybe conda has problems to install those exact two versions into one env? Can you try changing the numbers or try to insall those tools locally into a conda env?

**Comment by YeHW** [comment]
Thank you.
I tried installing to a local conda env using mamba and it succeeded.
But with conda, it failed with initial frozen solve.
I'll try replace samtools with pysam.

**Comment by YeHW** [comment]
Hi @bgruening, thanks for your suggestion and looks like it worked with `cnvkit=0.9.8,pysam=0.19.1` this time.
May I ask what I should do in order to be able to search the built container with the command:
`mulled-search --destination quay singularity --channel bioconda --search cnvkit pysam | grep "mulled"`
Thank you!

**Comment by bgruening** [comment]
Cool

**Pull request merged**
