### PR TITLE
gem3-mapper=3.6.1,samtools=1.6

### PR DESCRIPTION
**Pull request by miqalvarez**

### CODE REVIEW

**Comment by bgruening** [comment]
There are currently other PRs with similar containers: https://github.com/BioContainers/multi-package-containers/pull/2726

Can you please check if they work for you?

**Comment by miqalvarez** [comment]
`While checking build target: build target 'mulled-v2-240a9c1936dd6a68f46aa198b2629b6734a18428:8fc2f8fd66e104a88e3eec4d8fec1665ee7f7278-0' already exists. Use --force if you want to overwrite it`

Do I need to generate a new hash using the https://biocontainers.pro/multipackage ?

**Comment by bgruening** [comment]
If this container already exists, it should already work. I'm not sure I understand your use case.

Have you tried using `docker run -i -t quay.io/biocontainers/mulled-v2-240a9c1936dd6a68f46aa198b2629b6734a18428:8fc2f8fd66e104a88e3eec4d8fec1665ee7f7278-0 bash`

Is that working for you?

**Comment by miqalvarez** [comment]
Nop, I'm getting this error:
`docker: Error response from daemon: unauthorized: access to the requested resource is not authorized.`

Basically we need the container for an nf-core module and speaking with the developers of a pipeline they told us that it was done here. We need gem3 which will do the alignment and then pass it through samtools to convert it.

What I don't understand is why this error occurred, or maybe I did the PR wrong (if so, I apologize for the mess).

**Comment by bgruening** [comment]
You created 2 identical containers in your commits, that have been causing the errors.

**Comment by miqalvarez** [comment]
I see thanks! Now I just have to wait right? First time sry hahaha

**Comment by bgruening** [comment]
It should be available after a few minutes after merge

**Comment by miqalvarez** [comment]
Still can't find it using `mulled-search --destination quay singularity -s gem3-mapper samtools`
The output shows the containers separately but there is no "mulled" one

**Comment by bgruening** [comment]
The name you see already above: `mulled-v2-240a9c1936dd6a68f46aa198b2629b6734a18428:8fc2f8fd66e104a88e3eec4d8fec1665ee7f7278-0`


And mulled-search shows you:

```
mulled-search --destination singularity -s gem3-mapper samtools 


The query returned the following result(s).
LOCATION     NAME                                                VERSION                                     COMMAND
singularity  gem3-mapper                                         3.6.1--h21aa3a5_0                           wget https://depot.galaxyproject.org
.....    
singularity  samtools                                            1.9--h91753b0_8                             wget https://depot.galaxyproject.org/singularity/samtools:1.9--h91753b0_8
singularity  mulled-v2-240a9c1936dd6a68f46aa198b2629b6734a18428  8fc2f8fd66e104a88e3eec4d8fec1665ee7f7278-0  wget https://depot.galaxyproject.org/singularity/mulled-v2-240a9c1936dd6a68f46aa198b2629b6734a18428:8fc2f8fd66e104a88e3eec4d8fec1665ee7f7278-0
```

Hope that helps!

**Pull request merged**
