### PR TITLE
Bump stacks, checking if all works as I understand it

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by mvdbeek** [comment]
Nice, that worked like expected, adding -0 didn't trigger another build, adding -1 triggered a new build.

**Comment by bgruening** [comment]
Cool! Ok ... what about a third column about the base image?

**Comment by mvdbeek** [comment]
Yep, I'll do that. The third column is already defined as `name_override` ... but I think that we can have the third column be the base image if we adjust mulled-build-files and instead of using a fixed meaning of the columns we parse the headers. That should be safe even if others are using the third column already.

**Comment by bgruening** [comment]
I will close this, it should be created automatically I think.

**Pull request closed without merging**
