### PR TITLE
Request r-base and vcftools container image

### PR DESCRIPTION
**Pull request by mribeirodantas**

### CODE REVIEW

**Comment by mribeirodantas** [comment]
Please, merge @bgruening 🙌 😅

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Your wish is my command.

**Comment by mribeirodantas** [comment]
Thanks, @bgruening, but I think [something went wrong](https://github.com/BioContainers/multi-package-containers/actions/runs/6007652621/job/16294096153), right? Do you know what caused this?

**Comment by bgruening** [comment]
Small hiccup, a rerun fixed it.

**Comment by mribeirodantas** [comment]
@bgruening, let's say I forgot a package. If I edit the line with an extra package, will the same container image be rebuilt with the new package? No, right? 😅

Could you please confirm that I should add a new line instead with the new extra package?

**Comment by bgruening** [comment]
How can this happen ;)
Yes, you need to add a new line. If you can give me the old container name, maybe I find time to remove it to save a bit of storage and energy.

**Comment by mribeirodantas** [comment]
You can remove this container image, then. I need to add some extra R packages to it. I will do this eventually (add a new line), but for now this container image became useless to me.

**Comment by bgruening** [comment]
Done

**Comment by mribeirodantas** [comment]
Thanks, @bgruening !

**Pull request merged**
