### PR TITLE
Add pandoc to nanostring container

### PR DESCRIPTION
**Pull request by christopher-mohr**
We also need pandoc for this container, added pandoc 3.1.2.

### CODE REVIEW

**Comment by bgruening** [comment]
Why not using pandoc from its own container?

**Comment by christopher-mohr** [comment]
> Why not using pandoc from its own container?

Hi @bgruening, we need it for a nf-core pipeline, therefore it has to be in one container. Still need to find a compatible version though as I saw.

**Comment by bgruening** [comment]
Nexflow can not do the conversion in a second step?

**Comment by christopher-mohr** [comment]
We are using the render function of the [NACHO](https://github.com/mcanouil/NACHO) package which requires pandoc (and the other dependencies to my knowledge.
@apeltzer please correct me if I'm wrong.

**Comment by apeltzer** [comment]
Yes that's true - it's unfortunately not possible to pull this apart.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Please try to fix the versions... So that it turns green 💚 thanks.

**Comment by christopher-mohr** [comment]
> Please try to fix the versions... So that it turns green 💚 thanks.

✅

**Pull request merged**
