### PR TITLE
mulled container with bwa v0.7.17 and samtools v1.19.2

### PR DESCRIPTION
**Pull request by asp8200**
Needed for nf-core/sarek.

### CODE REVIEW

**Comment by maxulysse** [comment]
looks good to me, but some other lines were modified, my guess is that you have a linter in your vscode or something

**Comment by asp8200** [comment]
Oh, sorry about that. Is it a problem?

**Comment by maxulysse** [comment]
> Oh, sorry about that. Is it a problem?

no idea

**Comment by asp8200** [comment]
> > Oh, sorry about that. Is it a problem?
> 
> no idea

Let's see what the reviewers say

**Comment by bgruening** [comment]
Its ok :)

Thanks!

**Pull request merged**
