### PR TITLE
Add container mulled-v2-3a383a341e70f6cecbc5009756f04dbe57b09b3e:9865ca178e9ddafb01214ee3c3df7fb1f713f396.

### PR DESCRIPTION
**Pull request by dockerhub-toolshed**
**Hash**: mulled-v2-3a383a341e70f6cecbc5009756f04dbe57b09b3e:9865ca178e9ddafb01214ee3c3df7fb1f713f396

**Packages**:
- zip=3.0
- matplotlib=3.5.2
- xraylarch=0.9.71
Base Image:quay.io/bioconda/base-glibc-busybox-bash:latest

**For** :
- larch_artemis.xml
- larch_feff.xml

Generated with Planemo.

### CODE REVIEW

**Comment by mvdbeek** [comment]
@patrick-austin these are the containers being built

**Comment by patrick-austin** [comment]
> @patrick-austin these are the containers being built

Thanks @mvdbeek - if the CI fails to build the image then I suppose I'll need to debug, and if needed change dependencies in the tool repo, which gets monitored by planemo, then will produce a new PR here?

**Comment by bgruening** [comment]
They should normally not fail. Planemo is using exactly the same. So if you test your tools with planemo and Docker (as we recommend in IUC) the container is build-able - assuming the CI on your repo passed before you merged ;)

**Comment by patrick-austin** [comment]
> They should normally not fail. Planemo is using exactly the same. So if you test your tools with planemo and Docker (as we recommend in IUC) the container is build-able - assuming the CI on your repo passed before you merged ;)

Thanks @bgruening. Did have some trouble getting the tool repo CI to pass to begin with (timing out after 6 hours spent trying to resolve dependencies IIRC) and building containers via admin UI on our instance (possibly due to memory/storage limitations). So at this point I'm always prepared for things to break... But good to know that if the tool CI passes everything else **_should_** just work.

**Pull request merged**
