### PR TITLE
Add container mulled-v2-aff99a181f009389cd4d739067e4d513a55ece2d:f62d7b85bed85aadb2795d0b927f7e271d276c3d.

### PR DESCRIPTION
**Pull request by dockerhub-toolshed**
**Hash**: mulled-v2-aff99a181f009389cd4d739067e4d513a55ece2d:f62d7b85bed85aadb2795d0b927f7e271d276c3d

**Packages**:
- matplotlib=2.0.0
- biopython=1.67
- matplotlib-venn=0.11.5
- galaxy_sequence_utils=1.1.3

**For** :
- venn_list.xml

Generated with Planemo.

### CODE REVIEW

**Comment by bgruening** [comment]
ping @peterjc
This is the container for your tool. Please note that https://toolshed.g2.bx.psu.edu/view/peterjc/venn_list/ does not seem to be updated.

**Comment by peterjc** [comment]
Ha. Too efficient, I wanted to confirm an install from the Test Tool Shed worked (given the dependency changes) before pushing to the main Tool Shed:
https://github.com/peterjc/pico_galaxy/issues/32

**Comment by bgruening** [comment]
@peterjc as always very accurate :)

Just for your information, since we embraced conda I never check the TTS anymore. If tests are passing it also worked always on our instance.

**Comment by peterjc** [comment]
It is on the main TS now, thanks for working on the container side of things.

**Comment by bgruening** [comment]
@peterjc you should probably remove the tool_dependency file from the repo.

**Comment by peterjc** [comment]
I agree, https://github.com/peterjc/pico_galaxy/commit/6be5e3559fda63cae2fb72262952a429b3f47b11

**Pull request merged**
