### PR TITLE
Update hash.tsv with matchms 0.24.0-1

### PR DESCRIPTION
**Pull request by hechth**

### CODE REVIEW

**Comment by hechth** [comment]
@bgruening why does it say that matchms 0.24.0-1 doesn't exist if it does? https://bioconda.github.io/recipes/matchms/README.html

**Comment by bgruening** [comment]
It does not. build numbers you specify in a different way, like here: https://github.com/BioContainers/multi-package-containers/blob/4359bd9ed14ba4b1182d3e1cd382c7a5f6557556/combinations/hash.tsv#L94

But usually, you don't need to do that. The latest version should be picked by conda (in theory). So removing the build number is there the correct thing to do. You can check the CI logs if you get build 1.

**Comment by hechth** [comment]
So the double dash is for the build number?

**Comment by bgruening** [comment]
Yes, but this will also change the image name, because its a different version. Then you don't need a build bumb ;)

**Pull request merged**
