### PR TITLE
Scanpy Freiburg wrappers

### PR DESCRIPTION
**Pull request by pcm32**
For Scanpy inspect and others. Thanks!

### CODE REVIEW

**Comment by bgruening** [comment]
@pcm32 for which tools are those needed? Is this an IUC tool?

**Comment by pcm32** [comment]
Yes, IUC, plot with scanpy I think

**Comment by pcm32** [comment]
Or Scanpy inspect....  or both

**Comment by bgruening** [comment]
Mh, those containers should already exists ... IUC once are build automatiacally :(

**Comment by pcm32** [comment]
Yes, I can confirm that they work on our container based setup, so we don't need this PR here. Thanks @bgruening !

**Pull request closed without merging**
