### PR TITLE
Add container mulled-v2-9f42852121f611cb4daa9e9aa155f28f18e241fe:4772…

### PR DESCRIPTION
**Pull request by nuwang**
…f92039dda74c54152b92873730edc204f530.

**Hash**: mulled-v2-9f42852121f611cb4daa9e9aa155f28f18e241fe:4772f92039dda74c54152b92873730edc204f530

**Packages**:
- bioconductor-annaffy
- r-venndiagram
- bioconductor-org.hs.eg.db
- r-upsetr=1.3.3
- bioconductor-geoquery
- r-optparse
- bioconductor-affy
- r-metama
Base Image:bioconda/extended-base-image:latest

**For** :
- MetaMA.xml

Generated with Planemo.

### CODE REVIEW

**Comment by bgruening** [comment]
@nuwang do you know why those tools are not tracked?

**Comment by nuwang** [comment]
@bgruening These tools are coming from: https://github.com/sblanck/smagexp which are not in the monitored list. Should I just add them instead?

**Comment by nuwang** [comment]
The issue tracking this is: https://github.com/sblanck/smagexp/issues/3

**Comment by bgruening** [comment]
Sure why not, if this repo is going to be maintained. Please note that those tools are not secure and lacking some quotes etc ...

**Pull request merged**
