### PR TITLE
Update hash.tsv

### PR DESCRIPTION
**Pull request by ypriverol**
@bgruening: 
This is a container that will provide all the major tools to compress/decompress files including: unzip, gzip, tar, etc. If you think others are also useful, it would be nice to have them added.

### CODE REVIEW

**Comment by bgruening** [comment]
Is xz included?

**Comment by ypriverol** [comment]
Just added xz=5.2.9. Thanks for the suggestion.

**Comment by ypriverol** [comment]
> Just added xz=5.2.9. Thanks for the suggestion.

5.2.9 is broken apparently, checking 5.2.6.

**Comment by ypriverol** [comment]
@bgruening how do I know when the mulled container will be ready?

**Comment by bgruening** [comment]
Such a question after 6 years ;)

It is ready 20min after merge: https://quay.io/repository/biocontainers/mulled-v2-796b0610595ad1995b121d0b85375902097b78d4?tab=tags&tag=latest

**Comment by ypriverol** [comment]
😜 I actually know it, but after checking and see nothing was yet build, I prefer to double-check with you. Next time I wait the 20min/1h. Thanks a lot.

**Pull request merged**
