### PR TITLE
Add a container with cyvcf2 and click.

### PR DESCRIPTION
**Pull request by marksantcroos**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks Mark!

**Comment by marksantcroos** [comment]
@bgruening Thanks for the quick merge! I have some more combinations that I would like to add. Should I restrain myself or is more better?

**Comment by bgruening** [comment]
About how many thousands are we talking ;)
We have everything in backups and convert them also to Singularity, so there is overhead involved, but we try hard to support the community wherever we can.

**Comment by marksantcroos** [comment]
Haha, don't worry, I wasn't thinking about these numbers. I'm actually surprised this isn't used more yet, as single package per container has its limitations, especially when it's about python packages or so.

While we are at it, whats the further process now, before the container becomes available?

**Comment by bgruening** [comment]
Its already here: https://quay.io/repository/biocontainers/mulled-v2-e88f1ba37a8a785d7af0ad5738cc264627664a54

and here: https://depot.galaxyproject.org/singularity/

**Comment by marksantcroos** [comment]
Thanks!

**Pull request merged**
