### PR TITLE
create pybedtools and pandas container

### PR DESCRIPTION
**Pull request by yumisims**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @yumisims can you maybe add this to the hash.tsv file? https://github.com/BioContainers/multi-package-containers/blob/master/combinations/hash.tsv Thanks.

**Comment by yumisims** [comment]
added line to the hash.tsv

**Comment by priyanka-surana** [comment]
@bgruening Can you please merge this PR?

**Comment by bgruening** [comment]
This was done in https://github.com/BioContainers/multi-package-containers/pull/2531

Thanks everyone!

**Comment by priyanka-surana** [comment]
Thank you 👍

**Pull request closed without merging**
