### PR TITLE
add magus + pigz to hash.tsv

### PR DESCRIPTION
**Pull request by lrauschning**
Add a mulled container of magus and pigz for packaging in a module, same as my previous PRs.

### CODE REVIEW

**Comment by lrauschning** [comment]
Noticed magus needs an update to allow outputting to stdout without polluted output and wrote a fix, will reopen this when the fix is in bioconda.

**Comment by bgruening** [comment]
This needs a rebase.

**Comment by lrauschning** [comment]
Rebased.

**Comment by lrauschning** [comment]
No idea why adding the same container that earlier ran through is failing now – the CI run is not giving any error message either.
@bgruening do you have an idea why this is happening?

**Comment by bgruening** [comment]
Thanks

**Pull request merged**
