### PR TITLE
Add container mulled-v2-eb9e7907c7a753917c1e4d7a64384c047429618a:d4ca6cb58c17558e45d789d552f8d20c2f0cf912.

### PR DESCRIPTION
**Pull request by dockerhub-toolshed**
**Hash**: mulled-v2-eb9e7907c7a753917c1e4d7a64384c047429618a:d4ca6cb58c17558e45d789d552f8d20c2f0cf912

**Packages**:
- samtools=1.9
- deeptools=3.2.1

**For** :
- multiBamSummary.xml
- plotCorrelation.xml
- bamCompare.xml
- plotEnrichment.xml
- bamPEFragmentSize.xml
- correctGCBias.xml
- bigwigCompare.xml
- plotFingerprint.xml
- multiBigwigSummary.xml
- plotProfiler.xml
- plotPCA.xml
- bamCoverage.xml
- alignmentSieve.xml
- computeMatrixOperations.xml
- computeMatrix.xml
- plotCoverage.xml
- estimateReadFiltering.xml
- computeGCBias.xml
- plotHeatmap.xml

Generated with Planemo.

### CODE REVIEW

**Comment by bgruening** [comment]
ping @dpryan79

**Comment by dpryan79** [comment]
Thanks, want to take care of the Galaxy wrappers? :)

**Comment by bgruening** [comment]
@dpryan79 done.

**Comment by dpryan79** [comment]
Thanks!

**Pull request merged**
