### PR TITLE
add r-sceasy plus anndata package

### PR DESCRIPTION
**Pull request by fmalmeida**
Adding a mulled container that contains the three required packages to have a full [sceasy](https://github.com/cellgeni/sceasy) installation.

* anndata
* sceasy
* scipy

### CODE REVIEW

**Comment by fmalmeida** [comment]
Sorry that it seems to not be required as the main package may have it.

**Comment by fmalmeida** [comment]
Reopening because the existing bioconda container is not working.

**Comment by fmalmeida** [comment]
Hi @bgruening,

When I run the following command when using the available biocontainer:

```R
#!/usr/bin/env Rscript
library(sceasy)
library(reticulate)

args <- commandArgs(trailingOnly=TRUE)

h5ad_file     <- args[1]
out_prefix    <- args[2]
out_file      <- paste(
    out_prefix, ".rds", sep = ""
)

sceasy::convertFormat(
    h5ad_file, 
    from="anndata", 
    to="seurat",
    outFile=out_file
)
```

I receive the following:

```bash
Command error:
  Loading required package: reticulate
  Warning messages:
  1: package ‘sceasy’ was built under R version 4.0.3 
  2: package ‘reticulate’ was built under R version 4.0.3 
  /Users/fal/miniconda3/bin/conda: line 3: import: command not found
  /Users/fal/miniconda3/bin/conda: line 6: syntax error near unexpected token `sys.argv'
  /Users/fal/miniconda3/bin/conda: line 6: `if len(sys.argv) > 1 and sys.argv[1].startswith('shell.') and sys.path and sys.path[0] == '':'
  Error: Error 2 occurred creating conda environment r-reticulate
  Execution halted
```

I think something went wrong in the building of the biocontainer itself. I don't know much about the technicallities. But I am not sure if it you work on the mulled container as well.

Is it possible to create a local mulled copy before it actually being available in the repo? If yes, I can then change it to `draft` and maybe close it if a see that the mulled alternative would result in the same.

**Comment by bgruening** [comment]
What is the container name? I think a python file is executed as bash script here.

**Comment by fmalmeida** [comment]
I am using the latest quay.io container for this package: https://bioconda.github.io/recipes/r-sceasy/README.html

**Comment by bgruening** [comment]
If this is not working the conda package needs to be fixed. Then there is something wrong with the conda package I assume or actually with the upstream tool.

**Pull request closed without merging**
