### PR TITLE
python=3.9,pysam,biopython,click,pandas,numpy,ete3

### PR DESCRIPTION
**Pull request by nhhaidee**
Please help review and merge this PR. Thanks

### CODE REVIEW

**Comment by bgruening** [comment]
Please check your PR. There is a lot of junk included in your PR.

**Comment by nhhaidee** [comment]
These are packages that I need. I am not sure which packages are junk. Thanks

**Comment by bgruening** [comment]
@nhhaidee please look at your PR https://github.com/BioContainers/multi-package-containers/pull/1725/files ... you added 7 files that should not be in this PR.

**Comment by nhhaidee** [comment]
Oh No, sorry about that, only changes on hash.tsv should be committed.

**Pull request closed without merging**
