### PR TITLE
Bump pgx-variant-tools=0.0.2=py_2,locus_processing=0.0.4,snakemake-minimal=5.10.0,biopython=1.76,pyyaml=3.12

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by mvdbeek** [comment]
Ping @marksantcroos , this looks right now, it builds 'pgx-variant-tools=0.0.2=py_2,locus_processing=0.0.4,snakemake-minimal=5.10.0,biopython=1.76,pyyaml=3.12' as `quay.io/biocontainers/mulled-v2-f642d1155e8e31eb7e6658d490a748789c8de063:473eb72123053c532175b0819928922119fd5123-1`.

We updated the format of hash.tsv so that you can bump the build numbers. That is why just changing the conda build suffix didn't build a new container in the last build. The container that did actually get build had a wrong version specification (`==` instead of `=`). This should now work as expected.

**Comment by marksantcroos** [comment]
That looks better indeed! Thanks!
So one remaining question, can I update lines (apart from the build number), or should I always add a new entry?

**Comment by bgruening** [comment]
A new line would be nice.

**Comment by marksantcroos** [comment]
Thanks both, much appreciated!

**Pull request merged**
