### PR TITLE
Add container genform:r8.

### PR DESCRIPTION
**Pull request by dockerhub-toolshed**
**Hash**: genform:r8

**Packages**:
- genform=r8
Base Image:bgruening/busybox-bash:0.1

**For** :
- genform.xml

Generated with Planemo.

### CODE REVIEW

**Comment by bgruening** [comment]
Mh, why is this created? There is nothing new and it is a single tool container from bioconda?

**Comment by bgruening** [comment]
I will cancel the build ...

**Comment by mvdbeek** [comment]
Do you know which repo this is from ?

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/planemo/blob/1d7428643caa3407c5af2b3ee3bc0f9251994996/planemo/commands/cmd_container_register.py#L122 is a little too naive, but mulled-build-files has this right, so it should be an easy fix.

**Comment by bgruening** [comment]
Ok ... Let me know if its too complicated that we revert the commit on the monitor repo.

**Comment by mvdbeek** [comment]
I think I got it, just polishing this a little.

**Comment by mvdbeek** [comment]
Yep:
```
Handling conda_targets [frozenset({CondaTarget[genform,version=r8]})]
urllib3.connectionpool DEBUG 2020-01-30 10:56:15,831: Starting new HTTPS connection (1): conda.anaconda.org:443
urllib3.connectionpool DEBUG 2020-01-30 10:56:15,976: https://conda.anaconda.org:443 "GET /bioconda/linux-64/genform-r8-hc9558a2_0.tar.bz2 HTTP/1.1" 200 80940
urllib3.connectionpool DEBUG 2020-01-30 10:56:16,012: Starting new HTTPS connection (1): quay.io:443
urllib3.connectionpool DEBUG 2020-01-30 10:56:16,555: https://quay.io:443 "GET /api/v1/repository/biocontainers/genform HTTP/1.1" 200 610
quay repository already exists, skipping
```

Should we just try this from my planemo branch ?

**Comment by bgruening** [comment]
Yes, no release needed, try from the branch. :+1:

**Pull request closed without merging**
