### PR TITLE
create mirtop samtools r-base container

### PR DESCRIPTION
**Pull request by lpantano**
new container for nf-core/smrnaseq pipeline

### CODE REVIEW

**Comment by lpantano** [comment]
@drpatelh, any chance you can approve this running workflow? I am a first-time contributor :)

**Comment by bgruening** [comment]
its running now

**Comment by lpantano** [comment]
thank you @bgruening ! it seems it passed the test!

**Comment by bgruening** [comment]
Thanks!

**Comment by lpantano** [comment]
@bgruening, very naive question, how I can know the container ID to pull this docker? I tried this search `mulled-search --destination quay --channel bioconda --search mirtop samtools | grep mulled` but it doesn't return any value. Thanks in advance!

**Comment by lpantano** [comment]
oh well, I got it, I need to put the three tools. sorry.

**Pull request merged**
