### PR TITLE
bwa=0.7.17+samtools=1.9+bcftools=1.9

### PR DESCRIPTION
**Pull request by tamuanand**
Requesting multi-container with 3 tools (bwa=0.7.17,samtools=1.9,bcftools=1.9)

### CODE REVIEW

**Comment by bgruening** [comment]
? I will cancell the other one than.

**Comment by tamuanand** [comment]
Hi @bgruening 

Actually it would benefit to have the other build too

In 70% scenarios, bwa is always done followed by samtools

In most other scenarios, bwa is followed by samtools and bcftools

If the final size of bwa+samtools+bcftools is not that large compared to bwa+samtools, then it would make sense to cancel the other build (https://github.com/BioContainers/multi-package-containers/pull/1780)

If however, this trio makes it large, I would still recommend having bwa+samtools

Thanks

**Comment by bgruening** [comment]
> In 70% scenarios, bwa is always done followed by samtools

Yeah, that's why we have already 10 containers of that combination :)

> If the final size of bwa+samtools+bcftools is not that large compared to bwa+samtools, then it would make sense to cancel the other build (#1780)

Thats what I think as well. Just take the trio for both use cases.

**Comment by tamuanand** [comment]
Hi @bgruening 

How do I find out if this multicontainer is available via https://biocontainers.pro/registry?all_fields_search=bcftools&sort_order=asc&sort_field=default&offset=0&limit=30

Thanks again

**Comment by tamuanand** [comment]
I looked at the build and could find that this is available via
```
quay.io/biocontainers/mulled-v2-4341eda614564d45dca79a80cb2bb68ee42bb148:2d1a988d16fc0949a2975794b76548623407d297-0
```
The size of this trio comes out 312MB whereas bwa+samtools is 176MB (where bwa=0.7.17 and samtools=1.12 from quay.io/biocontainers/mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40:66ed1b38d280722529bb8a0167b0cf0
2f8a0b488-0)

Given the huge size difference, I would still request not to cancel the other build (#1780)

> Hi @bgruening
> 
> How do I find out if this multicontainer is available via https://biocontainers.pro/registry?all_fields_search=bcftools&sort_order=asc&sort_field=default&offset=0&limit=30
> 
> Thanks again

**Pull request merged**
