### PR TITLE
Add 3 computational chemistry containers

### PR DESCRIPTION
**Pull request by simonbray**

### CODE REVIEW

**Comment by simonbray** [comment]
@bgruening sorry, I realised I need some more

**Comment by bgruening** [comment]
Mh are the chemical tools tracked by planemo monitor?

**Review by bgruening — APPROVED** [review]

**Comment by simonbray** [comment]
Thanks again! No they are not, I'll add them

**Comment by bgruening** [comment]
That explains it! As soon as they are added those PRs are created automatically

**Comment by simonbray** [comment]
@bgruening correction, they were tracked but it looks like the link was broken: https://github.com/galaxyproject/planemo-monitor/commit/569ff88d45e5f3a50c91468aef1f7c6a69774189

**Pull request merged**
