### PR TITLE
Build bowtie2=2.4.2,samtools=1.11,pigz=2.3.4

### PR DESCRIPTION
**Pull request by charlotte-west**

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
Thanks @charlotte-west

**Comment by drpatelh** [comment]
You just saved me a PR @charlotte-west !! Saw the latest commit et voila!

**Comment by drpatelh** [comment]
@bgruening is there an easier way to see if multi-tool containers are available for certain tools and which versions they contain? I looked [here](https://biocontainers.pro/tools/mulled-v2-73670ad0b275d2b3ac5608694d2ca11a4ec7cc85) but those images haven't been updated in a while. I tend to look directly on [quay.io](https://quay.io/repository/biocontainers/bowtie2?tab=tags) for single tool images to get the latest versions but I am hoping that I am being completely naive here :)

**Comment by bgruening** [comment]
@drpatelh you can use `mulled-search` for example: https://docs.galaxyproject.org/en/latest/admin/special_topics/mulled_containers.html#search-for-containers - however, this is not really searching in the containers, it builds the hash and checks if the hash is available. My proposal would be that Nextflow is finally implementing the hashing for you, so this can happen automatically by just specifying the dependencies.

**Comment by drpatelh** [comment]
Thanks @bgruening! I will give this a spin and come back to you if I have any questions. I didn't quite understand the proposal for use with Nextflow? Would this adhere to version control for each tool and fetching exactly the same container for reproducibility purposes? I agree that it would be great to just give Nextflow a list of Conda dependencies with exact versions and allow it to pull the appropriate Docker / Singularity image but what if the build changes for example? At the moment I am explicitly specifying the containers after finding them like [here](https://github.com/nf-core/modules/blob/daa25b9329fd88ede4cc47ee83f73355f28ff79f/software/fastqc/main.nf#L14-L19) but it would be really nice to attempt to streamline this more.

**Pull request merged**
