### PR TITLE
add combination to hash.tsv

### PR DESCRIPTION
**Pull request by tillenglert**
Add:
r-tidyverse=2.0.0,r-knitr=1.43,r-dt=0.28,r-formattable=0.2.1,r-purrr=1.0.1,r-vegan=2.6_4,r-rmarkdown=2.22,r-optparse=1.7.3,r-ggplot2=3.4.2,r-dplyr=1.1.2,r-data.table=1.14.8,r-base=4.2.3,pandoc=2.19.2,r-dtplyr=1.3.1,r-patchwork=1.1.2

### CODE REVIEW

**Comment by tillenglert** [comment]
Hello there! Thanks for triggering the ci's! :)

This is weird if I install r-kfigr with conda it finds a package! Let me check if that package is really required, if not I will just take it out!

**Comment by bgruening** [comment]
We only support conda-forge and bioconda as channels, make sure it's in there.

**Comment by tillenglert** [comment]
It seems to exist only in anaconda/r/noarch so I will take it out! :)

**Comment by tillenglert** [comment]
I updated the branch and committed some changes, but it doesn't show here, do I need to reopen the PR?

**Comment by bgruening** [comment]
No, just commit and push to this branch. This should work.

**Comment by tillenglert** [comment]
Okay works again! I removed the r-kfigr package and it should build now :)

**Comment by bgruening** [comment]
Thanks!

**Comment by tillenglert** [comment]
Thank you @bgruening 🙂

**Comment by tillenglert** [comment]
Hi @bgruening again,

I just tried using the container, but I get the following error:

/usr/local/bin/pandoc: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory

pandoc is present, but doesn't seem to work, could this be linked to the base image? I'm wondering if changing to the Debian base image instead could help?

Thank you for your assistance!

**Pull request merged**
