### PR TITLE
Multi-tool containers for some ebi-gxa SC tools

### PR DESCRIPTION
**Pull request by pcm32**
This PR adds multi tools configs for the dependencies of:

_ensembl_gtf2gene_list
_salmon_kallisto_mtx_to_10x
dropletBarcodePlot

Question: can this be done without pinning versions on all packages? The original galaxy tools for these not pinned to a particular version of the tools.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Pinning the version is always preferable, you cannot know when one of the dependencies becomes incompatible. Not a major issue for containers (except a build issue here), but still better for reproducibility.

**Comment by pcm32** [comment]
I'll try to find the version numbers, I'll have to find existing conda envs for these, look up versions and then change the galaxy wrappers to use those versions...

**Comment by bgruening** [comment]
@pcm32 we usually pin all version that we specify in a Galaxy tool.

**Comment by pcm32** [comment]
@bgruening the problem I currently have is that is very difficult for me to know the versions; I have a number of mulled environments in the conda setup where those Galaxy tools where used. I don't see anything in the galaxy interface for jobs of those tools that can tell me the exact mulled env used for those executions. Is there a way, where I can take the galaxy tool XML as it is written today, and figure out the mulled env hash so that I can do conda list inside those environments and pin the tool against versions of packages that are being used there? Thanks!

**Comment by pcm32** [comment]
I guess with this: https://docs.galaxyproject.org/en/release_19.09/lib/galaxy.tool_util.deps.mulled.html#galaxy.tool_util.deps.mulled.util.image_name

or there is something more straightforward?

**Comment by pcm32** [comment]
(the galaxy tools didn't have those versions pinned, that was the initial problem)

**Comment by pcm32** [comment]
I have sorted out versions @bgruening, are you happy for me to merge? Thanks

**Pull request merged**
