### PR TITLE
python=3.9,python=3.9,pysam,biopython,click,pandas,numpy

### PR DESCRIPTION
**Pull request by nhhaidee**
python=3.9,python=3.9,pysam,biopython,click,pandas,numpy

My previous build was failed so I updated packages list, please help review and merge PR

Thanks,
Hai

### CODE REVIEW

**Comment by nhhaidee** [comment]
Can anyone help review this PR? Thanks

**Comment by nhhaidee** [comment]
The image was built successfully.

**Comment by bgruening** [comment]
@nhhaidee there are a lot of files in this PR that do not belong here. Can you please review your PR when submitting?

**Comment by nhhaidee** [comment]
@bgruening Thank you. The list of packages that I wanted to build were failed when I specify version (due to conflict) so I have tried for several time. I close PR for now,  delete forked repo and start with new reviewed PR.

**Pull request closed without merging**
