### PR TITLE
Update hash.tsv

### PR DESCRIPTION
**Pull request by lucacozzuto**

### CODE REVIEW

**Comment by lucacozzuto** [comment]
Hi! Many thanks for this! How can I know the name of the final image?

**Comment by bgruening** [comment]
Can you try: https://biocontainers.pro/#/multipackage --> enter your package name here and get the name, or install https://pypi.org/project/galaxy-lib/ and use the mulled-search tool to search for containers or look at the CI system here.

**Comment by lucacozzuto** [comment]
So using mulled-search -s samblaster gives me only the samblaster images. The same is for the website. I don't see that image.

**Comment by bgruening** [comment]
You need to search for bwa=0.7.17,samtools=1.10,samblaster=0.1.24

**Comment by lucacozzuto** [comment]
Thanks, I don't get anything sorry!

**Pull request merged**
