### PR TITLE
Add vcftools and htslib

### PR DESCRIPTION
**Pull request by mribeirodantas**

### CODE REVIEW

**Comment by bgruening** [comment]
thanks @mribeirodantas

**Comment by mribeirodantas** [comment]
Thanks, @bgruening ! I was able to find the container image by pulling the image last added to quay.io/biocontainers, but I can't find it at https://biocontainers.pro/multipackage or with `mulled-search` from the `galaxy-tool-util` package.

Is it because it takes a while to update the search database? Is there any other way that could help me (and others) find this image?

**Comment by bgruening** [comment]
I'm not responsible for the registry and in fact, do not use it. I go directly to quay.io.
Tags are imho only possible to add via the Dockerfile builds, those ones here are automatic.

What have you tried with `mulled-search` that should be able to list your image? See https://github.com/BioContainers/multi-package-containers#searching-for-containers

**Comment by mribeirodantas** [comment]
I expected `mulled-search --destination quay -s vcftools tabix` to return my container image. Or looking for them by vcftools and/or tabix in here: https://biocontainers.pro/multipackage

Who is responsible for that? Who can help me understand how can I make this happen? 😄

**Comment by tamuanand** [comment]
Hi @mribeirodantas 

Were you looking for something like this below?  
- I use this snippet (as shown below) - https://gist.github.com/peterk87/c28167ceffbb36dcbcf5b5b225c4043d

```
python3 multi_container_mulled_hash.py "vcftools=0.1.14-0,htslib=1.3.1-0"
Packages                   : vcftools=0.1.14-0,htslib=1.3.1-0
# packages                 : 2
Mulled name                : mulled-v2-b9358559e3ae3b9d7d8dbf1f401ae1fcaf757de3:ac05763cf181a5070c2fdb9bb5461f8d08f7b93b
Image Name                 : mulled-v2-b9358559e3ae3b9d7d8dbf1f401ae1fcaf757de3
Version/Tag Name           : ac05763cf181a5070c2fdb9bb5461f8d08f7b93b
Quay.io URL                : https://quay.io/repository/biocontainers/mulled-v2-b9358559e3ae3b9d7d8dbf1f401ae1fcaf757de3
Docker pull command (quess): quay.io/biocontainers/mulled-v2-b9358559e3ae3b9d7d8dbf1f401ae1fcaf757de3:ac05763cf181a5070c2fdb9bb5461f8d08f7b93b-0

```

**Comment by mribeirodantas** [comment]
Thanks, @tamuanand ! 😉

**Comment by bgruening** [comment]
Its documented here: https://github.com/BioContainers/multi-package-containers#searching-for-containers

Can you provide me your bash command for mulled-search and the results? If its not working we should fix it :)

**Comment by mribeirodantas** [comment]
The following command returns no results: `mulled-search --destination quay -s vcftools`. `mulled-search --destination quay -s vcftools,htslib` neither.

**Pull request merged**
