### PR TITLE
Update hash.tsv

### PR DESCRIPTION
**Pull request by elisamaske**
Create container for pandas matplotlib seaborn tqdm statsmodels numpy scipy

### CODE REVIEW

**Comment by bgruening** [comment]
Please add versions.

**Comment by elisamaske** [comment]
I added the versions

**Comment by bgruening** [comment]
There is now a merge conflict

**Comment by bgruening** [comment]
> matplotlib 3.7.5**  does not exist (perhaps a typo ...

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
> [Sep  5 19:52:23] SOUT └─ matplotlib 3.7.4**  does not exist (perhaps a typo or a missing channel).

**Review by elisamaske — COMMENTED** [review]
I changed the versions once again, I hope this works now. Thank you!

**Pull request merged**
