### PR TITLE
Add samtools=1.9,bcftools=1.9 container

### PR DESCRIPTION
**Pull request by folago**

### CODE REVIEW

**Comment by mvdbeek** [comment]
Thanks @folago, would https://github.com/BioContainers/multi-package-containers/blob/8dfbedc5157a1a278ba49396a5da595e1466a98d/combinations/mulled-v2-f7a49c68bd00a9e0147f58c2f0ef0a7bd67e944b:0ed4ab8b3878aeff59493055e4d5510a4ac5c62f-0.tsv work for you ?

**Comment by folago** [comment]
Sure, that would work nicely.

**Comment by folago** [comment]
Oh sorry you meant there is one already, I just updated the PR.
I'll close this PR.

**Comment by mvdbeek** [comment]
Thanks, was thinking that might do, but if you specifically want `samtools=1.9,bcftools=1.9` there wouldn't be a problem merging this one either.

**Comment by folago** [comment]
I believe that both samtools and bcftools are based on htslib, so it would
be included anyways.

Maybe including it explicitly will add some source code and headers for
development?
Still negligible IMHO.

**Pull request closed without merging**
