### PR TITLE
Add ambertools=21.10 and gromacs=2020.2

### PR DESCRIPTION
**Pull request by simonbray**
These are only single package containers, I hope this is the right approach to trigger container creation.

### CODE REVIEW

**Comment by simonbray** [comment]
ping @bgruening

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Yes, this is correct if they are not in bioconda. Is gromacs not in bioconda?

**Comment by simonbray** [comment]
Yes, gromacs is in bioconda, but for some reason version 2020.2 never made it to BioContainers: https://biocontainers.pro/tools/gromacs :worried:

**Comment by bgruening** [comment]
Ok, strange.

**Comment by simonbray** [comment]
Thanks!

**Pull request merged**
