### PR TITLE
Add base_image and build_number to hash.tsv

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by mvdbeek** [comment]
Well, that didn't quite work out. With some debugging I see:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

Traceback (most recent call last):
  File "/Users/mvandenb/.pyenv/versions/3.6.9/bin/mulled-build-files", line 11, in <module>
    sys.exit(main())
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/galaxy/tool_util/deps/mulled/mulled_build_files.py", line 48, in main
    **args_to_mull_targets_kwds(args)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/galaxy/tool_util/deps/mulled/mulled_build.py", line 204, in mull_targets
    repo_data = quay_repository(repo_template_kwds["namespace"], repo_name)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/galaxy/tool_util/deps/mulled/util.py", line 54, in quay_repository
    data = response.json()
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mvdbeek** [comment]
Forgot about the newlines, this should work now.

**Comment by mvdbeek** [comment]
Yay, green now. What do you think @bgruening ? (I could also restore -- for the build suffix, both should work)

**Comment by bgruening** [comment]
@mvdbeek do you know why we get 3 new builds? No container should be build, isn't it?

**Comment by mvdbeek** [comment]
I only see one new build ? This is where the matplotlib specification was `==`, and since that was interpreted as the package name it just got a different hash on the initial build.

**Comment by mvdbeek** [comment]
`tensorflow=1.4.0,tensorboard=0.4.0rc3,matplotlib==2.1.0,numpy=1.13.3,scipy=0.19.1,libgcc`

**Comment by bgruening** [comment]
Ok, that explains it ...

**Pull request merged**
