### PR TITLE
An update to PR 2250 with R needed

### PR DESCRIPTION
**Pull request by tamuanand**
I submitted PR 2250, the tool combo was built. Most tools worked, However, some specific Picard Tools erred out with R requirement. Hence updating Line 273 with R

### CODE REVIEW

**Comment by tamuanand** [comment]
Hi @bgruening 

I had sent a message in PR 2250 about why that mulled tool did not work. https://github.com/BioContainers/multi-package-containers/pull/2250#issuecomment-1200038335

In this PR, I have updated L273 in hash.tsv with the R addition.

Sincerely apologise for any inconvenience.

On this PR, it looks like all tests have passed and it is ready to be merged.

I request you to review the same and have it merged.

Thanks in advance.

**Comment by bgruening** [comment]
@tamuanand we need a rebase here.

Just for the record you created a 500MB compressed container https://quay.io/repository/biocontainers/mulled-v2-44bba323f43b2a7ba9e704ac763d14407a8e66a9

Now you want to add R because picard did not work, which we fixed already in various picard containers. Your new container will add a few 100MB more that we need to store, mirror, and maintain. This is exactly why we, including nf-core, recommend using ONE container for ONE task. And not one container for multiple tasks. We just want to remove friction and reuse as much containers as possible.

**Comment by tamuanand** [comment]
Hi @bgruening 

Couple of things I would like to clarify 

- If you look at the bioconda gatk4 recipe - https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gatk4/meta.yaml#L18-L33- it has r-base mentioned and other `r-*` stuff.  Hence,  I am not sure why running the mulled container I requested in PR 2250 would fail with one of the tools complaining that R is required. Do I have to specify every single thing mentioned from the above highlighted section for the mulled tool creation?

> Just for the record you created a 500MB compressed container https://quay.io/repository/biocontainers/mulled-v2-44bba323f43b2a7ba9e704ac763d14407a8e66a9

I did write with my PR that it failed and hence, in the hash.tsv file, I did not add a new line. I edited Line 273 (my original request)  and added this spec. 
> Now you want to add R because picard did not work, which we fixed already in various picard containers. 

I agree with the stuff you have mentioned about nf-core etc, but in this situation my hands are tied and I need this combo to get my work going. I am pretty sure there are many other combos in the hash.tsv that have a larger docker image size at the end - I agree two wrongs do not make a right, but still..

That 500 MB docker from the mulled tool from PR 2250 would fail for others too - my suggestion is to delete it if possible.

**Comment by tamuanand** [comment]
@bgruening I request you to approve this PR and have the mulled tool created. If this new one does not work, I promise I will not make any new requests adding more stuff.

The files check says everything has passed successfully 

Hence, could you review/approve/merge this PR.

Thanks

**Comment by bgruening** [comment]
There is a merge conflict here, please resolve this one and we can proceed. Thanks.

**Comment by bgruening** [comment]
Outputs of GATK are defined here: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gatk4/meta.yaml#L42

And according to that, no R was installed: https://github.com/BioContainers/multi-package-containers/runs/7536180392?check_suite_focus=true#step:7:1269

**Comment by tamuanand** [comment]
Did so - please let me know if it looks OK
> There is a merge conflict here, please resolve this one and we can proceed. Thanks.

**Pull request merged**
