### PR TITLE
Update hash.tsv

### PR DESCRIPTION
**Pull request by DoaneAS**
singularity_BioContainer.tsv

### CODE REVIEW

**Comment by bgruening** [comment]
please don't remove the old entry, just add yours as well :)
Thanks.

**Comment by bgruening** [comment]
@DoaneAS I have fixed the tsv file, so you still need this container?

**Comment by DoaneAS** [comment]
Thanks @bgruening, yes I would still need the container, or I could also build it with a Singularity file. I'm just getting the hang of how it works... will container be hosted at [https://depot.galaxyproject.org/singularity/](https://depot.galaxyproject.org/singularity/) ?  I'm not sure I have the container ID, can I find it from the hash.tsv?

Thanks!

**Comment by bgruening** [comment]
Thanks @DoaneAS and sorry for being that slow.

**Pull request merged**
