### PR TITLE
Add container mulled-v2-879928bcdd8adc5b4660a3f6de3703d7c7861de4:6ce9…

### PR DESCRIPTION
**Pull request by pcm32**
…6688844d469d84f94fabb34055d8dfa283c7.

**Hash**: mulled-v2-879928bcdd8adc5b4660a3f6de3703d7c7861de4:6ce96688844d469d84f94fabb34055d8dfa283c7

**Packages**:
- python=3.7
- coreutils=8.30
Base Image:bgruening/busybox-bash:0.1

**For** :
- uniq.xml

Generated with Planemo.

### CODE REVIEW

**Comment by mvdbeek** [comment]
@bgruening This is weird, we should be building that one with dockerhub-toolshed as well. I wonder if some of the yml/cwl tools are breaking planemo-monitor.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/planemo-monitor/runs/1780945805?check_suite_focus=true#step:6:680

**Comment by pcm32** [comment]
I had to mess a bit with planemo monitor to make it work, although it was mostly the git part (it didn't like to make the push from my repo for some reason - so had to do that part manually).

**Comment by pcm32** [comment]
I had to mess a bit with planemo monitor to make it work, although it was mostly the git part (it didn't like to make the push from my repo for some reason - so had to do that part manually).

**Comment by mvdbeek** [comment]
We fixed planemo-monitor yesterday. https://github.com/galaxyproject/planemo/pull/1135/commits/5a6991c852b4ccab49f82ee31224305b2942cfa0 should recreate the PR. I'm going to close this one to make sure it's working now.

**Pull request closed without merging**
