### PR TITLE
Add pandas, seaborn,numpy, bottleneck

### PR DESCRIPTION
**Pull request by ekushele**
For [celfie](https://github.com/christacaggiano/celfie/blob/master/celfie_conda_env.yml)

### CODE REVIEW

**Comment by bgruening** [comment]
@ekushele thanks a lot!

**Comment by ekushele** [comment]
> @ekushele thanks a lot!

Thank you!

**Comment by ekushele** [comment]
@bgruening  when will I be able to download the mulled singularity image?

**Comment by bgruening** [comment]
Now, probably ...

**Pull request merged**
