### PR TITLE
gatk4, samtools, sambamba, bcftools, perl

### PR DESCRIPTION
**Pull request by tamuanand**
Hi

Can you  ignore Pull request https://github.com/BioContainers/multi-package-containers/pull/2249/

and instead use this request

I also needed perl there in that combo

Thanks

### CODE REVIEW

**Comment by bgruening** [comment]
xref: https://github.com/BioContainers/multi-package-containers/pull/2249

@tamuanand I don't really understand the argument of the huge file transfers, you can pipe one container into the other, can't you?

**Comment by tamuanand** [comment]
Hi @bgruening

I use awsbatch to manage my workflow where each process runs on a EC2 inside the container. Let's say I start with a 10GB Star transcriptome bam file, and use gatk ViewSam, the resulting output is 130GB

If I have to pipe this output to a different container I will be losing out a lot on network transfer of 130GB from EC2 to S3 and then again from S3 to a different EC2. 

To elaborate, if I have to get insertsize using a custom perl script, I would have to unnecessarily transfer 260 GB. If the container had perl, I could just pipe the output of ViewSam into perl within the same EC2 and be done with.

I have given a very simple use case above. 

The realtime needs are more complex and hence, this request of the 5 packages in a mulled container.

Thanks in advance

**Comment by tamuanand** [comment]
hi again @bgruening 

a quick follow up question: the PR page shows a green tick mark next to the title. Does this mean that this combo is available for docker pull at quay? 

Please advise. 

Thanks again

**Comment by bgruening** [comment]
> If I have to pipe this output to a different container I will be losing out a lot on network transfer of 130GB from EC2 to S3 and then again from S3 to a different EC2.

This is not what piping means, see here as an example. You do not need to write the result of one container to another.

https://stackoverflow.com/questions/47572671/attach-stdout-of-one-docker-container-to-stdin-of-another-docker-container

**Comment by tamuanand** [comment]
hi @bgruening Thanks for the SO link. I will look into it.

I would still request this mulled container as the workflow orchestrator I chose recommends 1 container per task 

Just checking - will this PR be merged. 

 Thanks

**Comment by bgruening** [comment]
> I would still request this mulled container as the workflow orchestrator I chose recommends 1 container per task 

That is exactly what I am saying :) You are trying here multiple tasks in one container, do you?

**Comment by bgruening** [comment]
A green checkbox means the container was build correctly, so is ready to be merged.

**Comment by tamuanand** [comment]
Hi @bgruening,

Thanks for the response.  I would like to know the standard turnaround time on this to be available as a mulled container - I would also like to request you or someone else to review this PR and have it merged as early as feasible

>A green checkbox means the container was build correctly, so is ready to be merged

Thanks for your time

**Comment by bgruening** [comment]
We can merge at any time. I just had the feeling the discussion was still open. See https://github.com/BioContainers/multi-package-containers/pull/2250#issuecomment-1197687789

**Comment by tamuanand** [comment]
Please go ahead and merge it as early as possible. One nf-core user asked me to send a message on biocontainers.gitter and I did that too

Looks like most people tag/bug you directly on gitter to have this pushed :)

Yes - please merge this PR and have the combo tool I requested made available. 

Thanks in advance

**Comment by tamuanand** [comment]
Yes - you are right. I want multiple tasks in 1 container 
> That is exactly what I am saying :) You are trying here multiple tasks in one container, do you?

**Comment by tamuanand** [comment]
Please go ahead and merge it as early as possible. One nf-core user asked me to send a message on biocontainers.gitter and I did that too

Looks like most people tag/bug you directly on gitter to have these things pushed :)

Yes - please merge this PR and have the combo tool I requested made available. 

Thanks in advance

**Comment by bgruening** [comment]
> Yes - you are right. I want multiple tasks in 1 container
> 
> > That is exactly what I am saying :) You are trying here multiple tasks in one container, do you?

Do you understand that this is against the recommendations of nf-core?

**Comment by tamuanand** [comment]
Yes, but nf-core also states this - https://nf-co.re/contributing/modules?q=mulled#software-requirements 

> Do you understand that this is against the recommendations of nf-core?

In my case, it is instead of bwa and samtools, it is gatk4 and sam/bcftools. Yes, I also have sambamba there - as you might be aware sambamba allows for better parallelization and is much more scalable than samtools. 

Thanks a lot for merging this PR.

**Comment by tamuanand** [comment]
Hi @bgruening 

Once again, thanks a lot for merging this PR. 

I have a follow up question: How do I get to know what I need to use to do the docker pull from quay.io

I see a long running thread (started by me) and you have couple of ways to search for mulled tools there, but they do not seem to pull up the tool combo I requested: https://github.com/BioContainers/multi-package-containers/issues/1737

Thanks

**Comment by tamuanand** [comment]
Hi @bgruening 

I was able to pull this mulled container and tried out different processes.  When it came to CollectRnaSeqMetrics, I got this message

`R is not installed on this machine. It is required for creating the chart`

I do not want to add a new line to hash.tsv  for this R requirement - Can I have this PR edited to also add `r-base=4.1.2` 

Please advise.

Thanks,
Anand

**Pull request merged**
