### PR TITLE
Update container for shm_csr

### PR DESCRIPTION
**Pull request by rhpvorderman**
Sorry, I missed two dependencies. I am truly sorry to bother again.

### CODE REVIEW

**Comment by bgruening** [comment]
@rhpvorderman do you know that planemo can create those PR for you when you have a working/tested tool?

https://github.com/BioContainers/multi-package-containers/pull/1932

**Comment by rhpvorderman** [comment]
Ah good to know! I guess these can also be bot merged because of the format?

**Comment by bgruening** [comment]
We could, but bot-merge is not yet implemented.

**Comment by rhpvorderman** [comment]
Thanks! The package works now!

**Pull request merged**
