### PR TITLE
Update hash.tsv

### PR DESCRIPTION
**Pull request by gmauro**
added bwa=0.7.1,samtools=1.6 combinations

### CODE REVIEW

**Comment by bgruening** [comment]
@gmauro welcome! :)

**Comment by gmauro** [comment]
@bgruening  Thank you. My first tentative with multi-package-containers

**Comment by gmauro** [comment]
building is failed but is not clear to me why.

**Comment by bgruening** [comment]
just restarted the build, lets see

**Comment by bgruening** [comment]
ah now I see, @ypriverol merged it but it was failing here as well.

**Comment by bgruening** [comment]
Ha, I know what it is. The container already exists :) 
https://github.com/BioContainers/multi-package-containers/blob/74c8cf140574c22640005370e88b8754d4fbea1a/combinations/mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40:1476e745a911a5a2ac22207311b275c51e745ba9-0.tsv

**Comment by gmauro** [comment]
But if I search for it on http://biocontainers.pro/multi-package-containers/, I can't find it

**Comment by bgruening** [comment]
@ypriverol will hate me for this, but please use `https://quay.io/repository/biocontainers/mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40` that is the source of truth. Everything else is a registry trying as good as it can to be up to date.

**Comment by bgruening** [comment]
Here the singularity one: https://depot.galaxyproject.org/singularity/mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40%3A03dc1d2818d9de56938078b8b78b82d967c1f820-0

**Pull request merged**
