### PR TITLE
Add combinations for PureCN

### PR DESCRIPTION
**Pull request by lbeltrame**
It is a bit long: this was taken out of the package namespace for PureCN. Notice that includes some optional dependencies to make the package fully usable. 

This was tested locally with mulled on a Singularity image.

### CODE REVIEW

**Comment by bgruening** [comment]
Why do you need so many packages in one container? Should this be a pureCN container? Is the https://quay.io/repository/biocontainers/bioconductor-purecn?tab=tags&tag=latest broken?

**Comment by lbeltrame** [comment]
It's not really usable alone. It lacks a lot of dependencies to be used (including command line usage) for specific options.

**Comment by lbeltrame** [comment]
FTR, this is being addressed in part at the bioconda level, see https://github.com/bioconda/bioconda-recipes/pull/40076
I'll update this PR with one or two containers with one added package only in addition to what bioconda will pull.

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
