### PR TITLE
enable `--use-mamba`

### PR DESCRIPTION
**Pull request by bernt-matthias**
I guess this needs a bit of testing. Suggestions?

### CODE REVIEW

**Comment by bgruening** [comment]
You could bump some build numbers in the hash.tsv file.

**Comment by bernt-matthias** [comment]
Looks good. At least I'm seeing `... conda` install --quiet --yes 'mamba=' ; fi && mamba install   .... ` in the output.

**Comment by bernt-matthias** [comment]
`'mamba='` looks odd .. but seems to work. Should we pin a specific mamba version. Or just let it use the latest?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
I think this is fine.

**Pull request merged**
