### PR TITLE
Add Python to Samtools/Bedtools Recipe

### PR DESCRIPTION
**Pull request by dstrib**
Add Python3.8 to the recently-added samtools/bedtools/facount recipe.

### CODE REVIEW

**Comment by bgruening** [comment]
Can you not run the python script as a second step? This will probably blow up the container by 200MB.

**Comment by dstrib** [comment]
@bgruening Unfortunately I'm using this as a drop-in replacement for an equivalent conda recipe in which python is available, and so rewriting the execution would not be ideal. Do you have any alternative suggestions to accomplish this?

**Comment by dstrib** [comment]
Further I am having a hard time identifying the resulting mulled container name. The utility at https://biocontainers.pro/#/multipackage will not allow me to browse a search query past the first page (both chrome and firefox) so I have not been able to see the result for my combination of packages. Do you have a recommended way to do this? Thanks! -Dan

**Comment by bgruening** [comment]
The conda package should be fixed :) Every dependency that is not needed should not be listed in the conda recipe but rather specified in an envinronemnt.yml file.

@dstrib you can not find the container yet as it was not merged. However, you can look up the container name here in the CI system or use `mulled search` on the command line to find your container. Workflow management systems like Galaxy will be smart enough to pull the container down for you without you specifying the name.

If you still need this PR, we can merge it, let me know.

**Comment by dstrib** [comment]
I am new to the BioContainers project, but would a better solution than adding Python as an explicit part of the recipe be to use a base image for this recipe that has Python 3.8+ installed? If so, do you have a suggestion as to which image this might be?
Thanks!

**Comment by bgruening** [comment]
Ok, will be available in a few minutes. Thanks and good luck for your research!

**Pull request merged**
