### PR TITLE
bwa with prinseq-plus-plus and perl

### PR DESCRIPTION
**Pull request by tamuanand**
Requesting bwa=0.7.17,prinseq-plus-plus=1.2.4,perl=5.32.1 combo

### CODE REVIEW

**Comment by tamuanand** [comment]
hi @martenson - Could you help me here and let me know where things are failing? Do I need to get a lower version perl?

**Comment by tamuanand** [comment]
hi @martenson 

I did that (lower perl) and it worked Could your review this PR and merge
Thanks

> hi @martenson - Could you help me here and let me know where things are failing? Do I need to get a lower version perl?

**Comment by tamuanand** [comment]
Hi @bgruening 

Can this PR be reviewed and merged 

Thanks

**Comment by bgruening** [comment]
Are you sure you want to use bwa and not bwa-mem?

**Comment by tamuanand** [comment]
Hi @bgruening 

Were you referring to bwa-mem2? 
>Are you sure you want to use bwa and not bwa-mem?

Yes, I would like to have the correct combo requested (and not bwa-mem2) 

Thanks

**Pull request merged**
