### PR TITLE
pysam=0.16.0.1,biopython=1.78

### PR DESCRIPTION
**Pull request by aunderwo**

### CODE REVIEW

**Comment by bgruening** [comment]
thanks @aunderwo

**Comment by aunderwo** [comment]
Thanks @bgruening 
How do I find out the docker image id on biocontainers?

**Comment by aunderwo** [comment]
Ah. I have it
```
mulled-search --destination quay singularity conda  --search pysam biopython  | grep "mulled"
```

**Comment by bgruening** [comment]
:) Enjoy!

**Pull request merged**
