### PR TITLE
container primarily for scikit-optimize with additional pandas and argparse requirements

### PR DESCRIPTION
**Pull request by charlotte-west**
Packages:

- scikit-optimize=0.9.0
- matplotlib=3.5.0
- pandas=1.3.5

For:
Running python scripts that can manipulate input data via pandas, optimize parameters (using scikit-optimize) and plot convergence figures.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @charlotte-west

**Comment by charlotte-west** [comment]
Sorry, I'm having trouble finding the container following this, do you know the name of it hosted on https://quay.io/organization/biocontainers or https://depot.galaxyproject.org/singularity/ ?

**Comment by bgruening** [comment]
Try this one here: quay.io/biocontainers/mulled-v2-4b8b79deff624848550279a662b5948d6508b3b8

**Comment by bgruening** [comment]
https://quay.io/repository/biocontainers/mulled-v2-4b8b79deff624848550279a662b5948d6508b3b8?tab=tags&tag=latest

**Comment by charlotte-west** [comment]
Thank you!

**Pull request merged**
