### PR TITLE
add old datamash

### PR DESCRIPTION
**Pull request by bernt-matthias**
Trying to get rid of conda envs. Need a container for an old version of: https://github.com/galaxyproject/tools-iuc/tree/main/tools/datamash

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Does not work because old bioconda build is not installable with strict channel priority.

**Comment by bgruening** [comment]
I have built it locally and pushed.

**Comment by bernt-matthias** [comment]
I would be interested in a systematic approach for creating containers for tools that are currently missing a container. 

Maybe we could use the toolshed (of a specified list of owners) instead of crawling github repos?

**Comment by bgruening** [comment]
@natefoo has something like that, at least a list of tools without containers. However, you will get a lot of old tool of course that even predates conda.

**Comment by natefoo** [comment]
I also have [a container](https://github.com/natefoo/usegalaxy.org-legacy-environment) I use for running tools with toolshed dependencies or conda dependencies inside singularity. Some ancient things are not worth the effort if you have a working copy of the dependencies already.

**Pull request closed without merging**
