### PR TITLE
Add pinned transit version

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by mvdbeek** [comment]
Damn, this got uploaded as quay.io/biocontainers/mulled-v2-98e94080f7dfc7de31b799237ba9a50efe3d7fd8:d3bc5b63772cbc63141b3e2a57ee38c4b60a055d-0 instead of mulled-v2-98e94080f7dfc7de31b799237ba9a50efe3d7fd8:b1fdad9795a35d257e267de57ccfb6e18d8da4f5-1.tsv
... which makes sense codewise, mulled-build-files is going to re-calculate the mulled name based on the targets column

**Comment by bgruening** [comment]
Should I revert this one? (removing the containers?)

**Comment by mvdbeek** [comment]
Yeah, that'd be good

**Comment by bgruening** [comment]
Done.

**Pull request merged**
