### PR TITLE
Add container mulled-v2-e4ce28f95c8ecbae44279615eb9417eac6ea0435:a4e86eb8f7a079b09d50aebf541291772ea0f931-0

### PR DESCRIPTION
**Pull request by DSchreyer**
Hash: mulled-v2-e4ce28f95c8ecbae44279615eb9417eac6ea0435:a4e86eb8f7a079b09d50aebf541291772ea0f931-0

Packages:
- python=2.7
- pysam=0.17.0
- flask=1.1.2
- cython=0.29.14
- numpy=1.16.6
- scipy=1.2.1
- matplotlib=2.2.5
- mosek::mosek=8.0.60

For:
- Run AmpliconArchitect.py (https://github.com/virajbdeshpande/AmpliconArchitect)

### CODE REVIEW

**Comment by bgruening** [comment]
Wouldn't it be better to create a bioconda package for this tool?

**Comment by DSchreyer** [comment]
Can I create a bioconda package even if I am not the original author and are not affiliated with the authors in any way?

**Comment by bgruening** [comment]
Of course :)

**Comment by DSchreyer** [comment]
@bgruening I tried to get it into bioconda, but failed. Mosek is not available on either bioconda or conda-forge and currently only supported on its own channel and therefore not possible to use in bioconda. Therfore, Is it possible to get a mulled-container for it? I will still try to get everything sorted but this probably takes many weeks.

**Comment by bgruening** [comment]
Thanks

**Pull request merged**
